"""Add Inquiry matching and human-gated Quotation facts.

Revision ID: 20260718_0017
Revises: 20260718_0016
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260718_0017"
down_revision = "20260718_0016"
branch_labels = None
depends_on = None

NOW = sa.text("CURRENT_TIMESTAMP")
JSON = sa.JSON().with_variant(postgresql.JSONB(none_as_null=True), "postgresql")
U = lambda: sa.Uuid(as_uuid=True)


def audit():
    return [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=NOW), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=NOW), sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)]


def tenant_fk(name):
    return sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name=name, ondelete="CASCADE")


def upgrade() -> None:
    op.create_table("customers", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("customer_code", sa.String(80), nullable=False), sa.Column("company_name", sa.String(300), nullable=False), sa.Column("country_code", sa.String(2)), sa.Column("language", sa.String(20), nullable=False), sa.Column("default_currency", sa.String(3), nullable=False), sa.Column("status", sa.String(20), nullable=False), *audit(), sa.CheckConstraint("status IN ('PROSPECT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')", name="ck_customers_status_allowed"), tenant_fk("fk_customers_tenant"), sa.UniqueConstraint("tenant_id", "id", name="uq_customers_tenant_identity"), sa.UniqueConstraint("tenant_id", "customer_code", name="uq_customers_tenant_code"))
    op.create_index("ix_customers_tenant_name", "customers", ["tenant_id", "company_name"])
    op.create_table("inquiries", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("inquiry_number", sa.String(80), nullable=False), sa.Column("customer_id", U()), sa.Column("temporary_customer_name", sa.String(300)), sa.Column("source_type", sa.String(30), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("language", sa.String(20), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("owner_membership_id", U(), nullable=False), sa.Column("version", sa.BigInteger(), nullable=False), *audit(), sa.CheckConstraint("status IN ('DRAFT', 'NEEDS_REVIEW', 'MATCHING', 'NEEDS_SELECTION', 'READY_FOR_QUOTE', 'QUOTED', 'CLOSED')", name="ck_inquiries_status_allowed"), sa.CheckConstraint("version >= 1", name="ck_inquiries_version_positive"), sa.CheckConstraint("customer_id IS NOT NULL OR temporary_customer_name IS NOT NULL", name="ck_inquiries_customer_context_required"), tenant_fk("fk_inquiries_tenant"), sa.ForeignKeyConstraint(["tenant_id", "customer_id"], ["customers.tenant_id", "customers.id"], name="fk_inquiries_tenant_customer", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "owner_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_inquiries_tenant_owner", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_inquiries_tenant_identity"), sa.UniqueConstraint("tenant_id", "inquiry_number", name="uq_inquiries_tenant_number"))
    op.create_index("ix_inquiries_tenant_status_updated", "inquiries", ["tenant_id", "status", "updated_at"])
    op.create_table("inquiry_items", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("inquiry_id", U(), nullable=False), sa.Column("line_number", sa.Integer(), nullable=False), sa.Column("raw_requirement", sa.Text(), nullable=False), sa.Column("normalized_requirement", JSON, nullable=False), sa.Column("quantity", sa.Numeric(20, 6)), sa.Column("unit_code", sa.String(32)), sa.Column("target_price", sa.Numeric(20, 6)), sa.Column("target_currency", sa.String(3)), sa.Column("image_search_id", U()), sa.Column("source_evidence_id", U()), sa.Column("status", sa.String(20), nullable=False), sa.Column("version", sa.BigInteger(), nullable=False), *audit(), sa.CheckConstraint("line_number >= 1", name="ck_inquiry_items_line_number_positive"), sa.CheckConstraint("quantity IS NULL OR quantity > 0", name="ck_inquiry_items_quantity_positive"), sa.CheckConstraint("version >= 1", name="ck_inquiry_items_version_positive"), sa.CheckConstraint("status IN ('DRAFT', 'CONFIRMED', 'MATCHED', 'SELECTED', 'NO_MATCH')", name="ck_inquiry_items_status_allowed"), tenant_fk("fk_inquiry_items_tenant"), sa.ForeignKeyConstraint(["tenant_id", "inquiry_id"], ["inquiries.tenant_id", "inquiries.id"], name="fk_inquiry_items_tenant_inquiry", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "image_search_id"], ["image_searches.tenant_id", "image_searches.id"], name="fk_inquiry_items_tenant_image_search", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_inquiry_items_tenant_identity"), sa.UniqueConstraint("tenant_id", "inquiry_id", "line_number", name="uq_inquiry_items_line"))
    op.create_index("ix_inquiry_items_tenant_inquiry_status", "inquiry_items", ["tenant_id", "inquiry_id", "status"])
    op.create_table("inquiry_match_results", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("inquiry_item_id", U(), nullable=False), sa.Column("product_id", U(), nullable=False), sa.Column("sku_id", U()), sa.Column("supplier_product_id", U()), sa.Column("product_version", sa.BigInteger(), nullable=False), sa.Column("rank", sa.Integer(), nullable=False), sa.Column("total_score", sa.Numeric(7, 6), nullable=False), sa.Column("score_breakdown", JSON, nullable=False), sa.Column("reasons", JSON, nullable=False), sa.Column("gaps", JSON, nullable=False), sa.Column("evidence", JSON, nullable=False), sa.Column("ranking_version", sa.String(80), nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("selected_by_membership_id", U()), sa.Column("selected_at", sa.DateTime(timezone=True)), *audit(), sa.CheckConstraint("rank >= 1", name="ck_inquiry_match_results_rank_positive"), sa.CheckConstraint("total_score >= 0 AND total_score <= 1", name="ck_inquiry_match_results_total_score_range"), sa.CheckConstraint("product_version >= 1", name="ck_inquiry_match_results_product_version_positive"), sa.CheckConstraint("status IN ('CANDIDATE', 'SELECTED', 'REJECTED')", name="ck_inquiry_match_results_status_allowed"), tenant_fk("fk_inquiry_match_results_tenant"), sa.ForeignKeyConstraint(["tenant_id", "inquiry_item_id"], ["inquiry_items.tenant_id", "inquiry_items.id"], name="fk_inquiry_match_results_tenant_item", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "product_id"], ["products.tenant_id", "products.id"], name="fk_inquiry_match_results_tenant_product", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "sku_id"], ["skus.tenant_id", "skus.id"], name="fk_inquiry_match_results_tenant_sku", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "supplier_product_id"], ["supplier_products.tenant_id", "supplier_products.id"], name="fk_inquiry_match_results_tenant_source", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "selected_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_inquiry_match_results_tenant_selector", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_inquiry_match_results_tenant_identity"), sa.UniqueConstraint("tenant_id", "inquiry_item_id", "ranking_version", "rank", name="uq_inquiry_match_results_rank"))
    op.create_index("ix_inquiry_match_results_tenant_item_status", "inquiry_match_results", ["tenant_id", "inquiry_item_id", "status"])
    op.create_table("quotations", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("quotation_number", sa.String(80), nullable=False), sa.Column("inquiry_id", U(), nullable=False), sa.Column("customer_id", U(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("current_version", sa.BigInteger(), nullable=False), sa.Column("total_amount", sa.Numeric(20, 2), nullable=False), sa.Column("created_by_membership_id", U(), nullable=False), sa.Column("approved_by_membership_id", U()), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("expires_at", sa.DateTime(timezone=True)), *audit(), sa.CheckConstraint("status IN ('DRAFT', 'CALCULATED', 'NEEDS_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED')", name="ck_quotations_status_allowed"), sa.CheckConstraint("current_version >= 1", name="ck_quotations_current_version_positive"), sa.CheckConstraint("total_amount >= 0", name="ck_quotations_total_amount_nonnegative"), tenant_fk("fk_quotations_tenant"), sa.ForeignKeyConstraint(["tenant_id", "inquiry_id"], ["inquiries.tenant_id", "inquiries.id"], name="fk_quotations_tenant_inquiry", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "customer_id"], ["customers.tenant_id", "customers.id"], name="fk_quotations_tenant_customer", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "created_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_quotations_tenant_creator", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "approved_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_quotations_tenant_approver", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_quotations_tenant_identity"), sa.UniqueConstraint("tenant_id", "quotation_number", name="uq_quotations_tenant_number"))
    op.create_index("ix_quotations_tenant_status_updated", "quotations", ["tenant_id", "status", "updated_at"])
    op.create_table("quotation_versions", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("quotation_id", U(), nullable=False), sa.Column("version_number", sa.BigInteger(), nullable=False), sa.Column("snapshot", JSON, nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("total_amount", sa.Numeric(20, 2), nullable=False), sa.Column("rule_version", sa.String(80), nullable=False), sa.Column("created_by_membership_id", U(), nullable=False), *audit(), sa.CheckConstraint("version_number >= 1", name="ck_quotation_versions_version_number_positive"), sa.CheckConstraint("total_amount >= 0", name="ck_quotation_versions_total_amount_nonnegative"), tenant_fk("fk_quotation_versions_tenant"), sa.ForeignKeyConstraint(["tenant_id", "quotation_id"], ["quotations.tenant_id", "quotations.id"], name="fk_quotation_versions_tenant_quotation", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "created_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_quotation_versions_tenant_creator", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_quotation_versions_tenant_identity"), sa.UniqueConstraint("tenant_id", "quotation_id", "version_number", name="uq_quotation_versions_number"), sa.UniqueConstraint("tenant_id", "quotation_id", "content_hash", name="uq_quotation_versions_hash"))
    op.create_table("quotation_items", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("quotation_version_id", U(), nullable=False), sa.Column("inquiry_item_id", U(), nullable=False), sa.Column("product_id", U(), nullable=False), sa.Column("sku_id", U()), sa.Column("supplier_product_id", U(), nullable=False), sa.Column("product_snapshot", JSON, nullable=False), sa.Column("source_snapshot", JSON, nullable=False), sa.Column("quantity", sa.Numeric(20, 6), nullable=False), sa.Column("unit_code", sa.String(32), nullable=False), sa.Column("unit_cost", sa.Numeric(20, 6), nullable=False), sa.Column("target_margin_rate", sa.Numeric(7, 6), nullable=False), sa.Column("unit_price", sa.Numeric(20, 2), nullable=False), sa.Column("line_total", sa.Numeric(20, 2), nullable=False), sa.Column("warnings", JSON, nullable=False), *audit(), sa.CheckConstraint("quantity > 0", name="ck_quotation_items_quantity_positive"), sa.CheckConstraint("unit_cost >= 0 AND unit_price >= 0 AND line_total >= 0", name="ck_quotation_items_amounts_nonnegative"), sa.CheckConstraint("target_margin_rate >= 0 AND target_margin_rate < 1", name="ck_quotation_items_margin_range"), tenant_fk("fk_quotation_items_tenant"), sa.ForeignKeyConstraint(["tenant_id", "quotation_version_id"], ["quotation_versions.tenant_id", "quotation_versions.id"], name="fk_quotation_items_tenant_version", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "inquiry_item_id"], ["inquiry_items.tenant_id", "inquiry_items.id"], name="fk_quotation_items_tenant_inquiry_item", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "product_id"], ["products.tenant_id", "products.id"], name="fk_quotation_items_tenant_product", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "sku_id"], ["skus.tenant_id", "skus.id"], name="fk_quotation_items_tenant_sku", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "supplier_product_id"], ["supplier_products.tenant_id", "supplier_products.id"], name="fk_quotation_items_tenant_source", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_quotation_items_tenant_identity"), sa.UniqueConstraint("tenant_id", "quotation_version_id", "inquiry_item_id", name="uq_quotation_items_version_line"))
    op.create_table("quotation_approvals", sa.Column("id", U(), primary_key=True), sa.Column("tenant_id", U(), nullable=False), sa.Column("quotation_id", U(), nullable=False), sa.Column("quotation_version_id", U(), nullable=False), sa.Column("requested_by_membership_id", U(), nullable=False), sa.Column("decided_by_membership_id", U()), sa.Column("status", sa.String(20), nullable=False), sa.Column("reason", sa.Text()), sa.Column("decided_at", sa.DateTime(timezone=True)), *audit(), sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED')", name="ck_quotation_approvals_status_allowed"), tenant_fk("fk_quotation_approvals_tenant"), sa.ForeignKeyConstraint(["tenant_id", "quotation_id"], ["quotations.tenant_id", "quotations.id"], name="fk_quotation_approvals_tenant_quotation", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "quotation_version_id"], ["quotation_versions.tenant_id", "quotation_versions.id"], name="fk_quotation_approvals_tenant_version", ondelete="CASCADE"), sa.ForeignKeyConstraint(["tenant_id", "requested_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_quotation_approvals_tenant_requester", ondelete="RESTRICT"), sa.ForeignKeyConstraint(["tenant_id", "decided_by_membership_id"], ["memberships.tenant_id", "memberships.id"], name="fk_quotation_approvals_tenant_decider", ondelete="RESTRICT"), sa.UniqueConstraint("tenant_id", "id", name="uq_quotation_approvals_tenant_identity"), sa.UniqueConstraint("tenant_id", "quotation_version_id", name="uq_quotation_approvals_version"))
    if op.get_bind().dialect.name == "postgresql":
        tenant = "NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
        for table in ("customers", "inquiries", "inquiry_items", "inquiry_match_results", "quotations", "quotation_versions", "quotation_items", "quotation_approvals"):
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(f"CREATE POLICY {table}_tenant_isolation ON {table} FOR ALL USING (tenant_id = {tenant}) WITH CHECK (tenant_id = {tenant})")


def downgrade() -> None:
    for table in ("quotation_approvals", "quotation_items", "quotation_versions", "quotations", "inquiry_match_results", "inquiry_items", "inquiries", "customers"):
        op.drop_table(table)
