import type { UiLocale } from "./types";

const zh = {
  title: "商家自动增量翻译", enabled: "为此商家自动更新所有已发布语言", publish: "完成后自动发布语言包", delay: "统一合并等待（秒）",
  loading: "正在读取自动翻译状态", DISABLED: "自动翻译未开启", IDLE: "正在监控商品变化",
  WAITING: "等待自动翻译", QUEUED: "自动翻译已排队", RUNNING: "正在自动翻译", PAUSED: "翻译已暂停",
  ATTENTION: "有内容需要人工处理", READY: "译文已保存，等待发布", manual: "正在执行手动翻译",
  help: "开关按商家生效，会维护所有已发布语言；只处理开启后的新增或变更内容，不重跑历史翻译。首次使用请先发布语言包。",
  failure: "自动翻译状态读取失败", saved: "自动翻译设置已保存", save: "保存设置", retry: "重新读取",
};
type Copy = typeof zh;
const localized: Record<Exclude<UiLocale, "zh-CN">, Copy> = {
  "en-US": { title: "Merchant automatic translation", enabled: "Automatically update all published languages for this merchant", publish: "Publish language packs when ready", delay: "Unified merge delay (seconds)", loading: "Loading automatic translation status", DISABLED: "Automatic translation is off", IDLE: "Watching for product changes", WAITING: "Waiting for automatic translation", QUEUED: "Automatic translation queued", RUNNING: "Translating automatically", PAUSED: "Translation paused", ATTENTION: "Some content needs review", READY: "Translations saved, ready to publish", manual: "Manual translation in progress", help: "This switch applies to the merchant and all published languages. Only new or changed content after enabling is processed; existing translations are retained. Publish an initial language pack first.", failure: "Could not load automatic translation status", saved: "Automatic translation settings saved", save: "Save settings", retry: "Reload" },
  es: { title: "Traducción automática del comerciante", enabled: "Actualizar automáticamente todos los idiomas publicados de este comerciante", publish: "Publicar los paquetes al terminar", delay: "Espera de agrupación unificada (segundos)", loading: "Cargando el estado de traducción automática", DISABLED: "Traducción automática desactivada", IDLE: "Supervisando cambios de productos", WAITING: "Esperando traducción automática", QUEUED: "Traducción automática en cola", RUNNING: "Traduciendo automáticamente", PAUSED: "Traducción pausada", ATTENTION: "Hay contenido que requiere revisión", READY: "Traducciones guardadas, listas para publicar", manual: "Traducción manual en curso", help: "Este interruptor se aplica al comerciante y a todos los idiomas publicados. Solo se procesa contenido nuevo o modificado tras activar; se conservan las traducciones anteriores. Publique primero un paquete inicial.", failure: "No se pudo cargar el estado", saved: "Configuración guardada", save: "Guardar ajustes", retry: "Recargar" },
  tr: { title: "Satıcı otomatik çevirisi", enabled: "Bu satıcının yayımlanmış tüm dillerini otomatik güncelle", publish: "Hazır olduğunda dil paketlerini yayımla", delay: "Birleştirme beklemesi (saniye)", loading: "Otomatik çeviri durumu yükleniyor", DISABLED: "Otomatik çeviri kapalı", IDLE: "Ürün değişiklikleri izleniyor", WAITING: "Otomatik çeviri bekleniyor", QUEUED: "Otomatik çeviri sırada", RUNNING: "Otomatik çevriliyor", PAUSED: "Çeviri duraklatıldı", ATTENTION: "Bazı içerikler inceleme gerektiriyor", READY: "Çeviriler kaydedildi, yayımlanmaya hazır", manual: "Manuel çeviri sürüyor", help: "Bu anahtar satıcıya ve yayımlanmış tüm dillere uygulanır. Yalnızca etkinleştirmeden sonra eklenen veya değişen içerik işlenir; önceki çeviriler korunur. İlk dil paketini yayımlayın.", failure: "Çeviri durumu yüklenemedi", saved: "Ayarlar kaydedildi", save: "Ayarları kaydet", retry: "Yenile" },
  ar: { title: "الترجمة التلقائية للتاجر", enabled: "تحديث جميع اللغات المنشورة لهذا التاجر تلقائياً", publish: "نشر حزم اللغات عند اكتمالها", delay: "مدة تجميع التغييرات (ثوانٍ)", loading: "جارٍ تحميل حالة الترجمة التلقائية", DISABLED: "الترجمة التلقائية متوقفة", IDLE: "جارٍ مراقبة تغييرات المنتجات", WAITING: "في انتظار الترجمة التلقائية", QUEUED: "الترجمة التلقائية في قائمة الانتظار", RUNNING: "جارٍ الترجمة تلقائياً", PAUSED: "الترجمة متوقفة مؤقتاً", ATTENTION: "بعض المحتوى يحتاج إلى مراجعة", READY: "حُفظت الترجمات وهي جاهزة للنشر", manual: "الترجمة اليدوية قيد التنفيذ", help: "ينطبق هذا المفتاح على التاجر وجميع اللغات المنشورة. تُعالج الإضافات والتغييرات بعد التفعيل فقط، مع الاحتفاظ بالترجمات السابقة. انشر حزمة أولية أولاً.", failure: "تعذر تحميل حالة الترجمة", saved: "تم حفظ الإعدادات", save: "حفظ الإعدادات", retry: "إعادة التحميل" },
  ja: { title: "販売者の自動差分翻訳", enabled: "この販売者の公開済み言語をすべて自動更新", publish: "完了後に言語パッケージを公開", delay: "変更をまとめる待機時間（秒）", loading: "自動翻訳の状態を読み込み中", DISABLED: "自動翻訳は無効です", IDLE: "商品の変更を監視中", WAITING: "自動翻訳の開始待ち", QUEUED: "自動翻訳は待機列にあります", RUNNING: "自動翻訳中", PAUSED: "翻訳を一時停止しました", ATTENTION: "確認が必要な内容があります", READY: "翻訳を保存しました。公開待ちです", manual: "手動翻訳を実行中", help: "このスイッチは販売者と公開済みのすべての言語に適用されます。有効化後に追加・変更された内容のみを処理し、既存の翻訳は保持します。最初の言語パッケージを先に公開してください。", failure: "翻訳状態を読み込めませんでした", saved: "設定を保存しました", save: "設定を保存", retry: "再読み込み" },
  ko: { title: "판매자 자동 증분 번역", enabled: "이 판매자의 게시된 모든 언어 자동 업데이트", publish: "완료 후 언어 패키지 게시", delay: "변경 병합 대기 시간(초)", loading: "자동 번역 상태를 불러오는 중", DISABLED: "자동 번역 꺼짐", IDLE: "상품 변경 감시 중", WAITING: "자동 번역 대기 중", QUEUED: "자동 번역이 대기열에 있음", RUNNING: "자동 번역 중", PAUSED: "번역 일시 중지됨", ATTENTION: "일부 콘텐츠 검토 필요", READY: "번역 저장됨, 게시 대기 중", manual: "수동 번역 진행 중", help: "이 스위치는 판매자와 게시된 모든 언어에 적용됩니다. 활성화 후 추가되거나 변경된 내용만 처리하며 기존 번역은 유지됩니다. 먼저 초기 언어 패키지를 게시하세요.", failure: "번역 상태를 불러오지 못했습니다", saved: "설정이 저장되었습니다", save: "설정 저장", retry: "다시 불러오기" },
  pt: { title: "Tradução automática do comerciante", enabled: "Atualizar automaticamente todos os idiomas publicados deste comerciante", publish: "Publicar os pacotes quando estiverem prontos", delay: "Espera unificada para agrupar (segundos)", loading: "Carregando o estado da tradução automática", DISABLED: "Tradução automática desativada", IDLE: "Monitorando alterações nos produtos", WAITING: "Aguardando tradução automática", QUEUED: "Tradução automática na fila", RUNNING: "Traduzindo automaticamente", PAUSED: "Tradução pausada", ATTENTION: "Há conteúdo que precisa de revisão", READY: "Traduções salvas, prontas para publicar", manual: "Tradução manual em andamento", help: "Esta chave se aplica ao comerciante e a todos os idiomas publicados. Somente conteúdo novo ou alterado após ativar será processado; as traduções anteriores são mantidas. Publique primeiro um pacote inicial.", failure: "Não foi possível carregar o estado", saved: "Configurações salvas", save: "Salvar configurações", retry: "Recarregar" },
  fr: { title: "Traduction automatique du marchand", enabled: "Mettre à jour automatiquement toutes les langues publiées de ce marchand", publish: "Publier les packs une fois prêts", delay: "Délai de regroupement unifié (secondes)", loading: "Chargement de l’état de traduction automatique", DISABLED: "Traduction automatique désactivée", IDLE: "Surveillance des modifications de produits", WAITING: "En attente de traduction automatique", QUEUED: "Traduction automatique en file d’attente", RUNNING: "Traduction automatique en cours", PAUSED: "Traduction en pause", ATTENTION: "Certains contenus nécessitent une révision", READY: "Traductions enregistrées, prêtes à publier", manual: "Traduction manuelle en cours", help: "Ce bouton s’applique au marchand et à toutes les langues publiées. Seuls les ajouts et modifications après activation sont traités ; les anciennes traductions sont conservées. Publiez d’abord un pack initial.", failure: "Impossible de charger l’état", saved: "Paramètres enregistrés", save: "Enregistrer", retry: "Recharger" },
  fa: { title: "ترجمه خودکار تاجر", enabled: "همه زبان‌های منتشرشده این تاجر را به‌صورت خودکار به‌روزرسانی کن", publish: "بسته‌های زبان را پس از تکمیل منتشر کن", delay: "زمان انتظار تجمیع یکپارچه (ثانیه)", loading: "در حال دریافت وضعیت ترجمه خودکار", DISABLED: "ترجمه خودکار غیرفعال است", IDLE: "در حال پایش تغییرات محصولات", WAITING: "در انتظار ترجمه خودکار", QUEUED: "ترجمه خودکار در صف است", RUNNING: "در حال ترجمه خودکار", PAUSED: "ترجمه موقتاً متوقف شده است", ATTENTION: "بخشی از محتوا نیاز به بررسی دارد", READY: "ترجمه‌ها ذخیره شده و آماده انتشار هستند", manual: "ترجمه دستی در حال اجراست", help: "این کلید برای تاجر و همه زبان‌های منتشرشده اعمال می‌شود. فقط محتوای افزوده یا تغییرکرده پس از فعال‌سازی پردازش می‌شود و ترجمه‌های قبلی حفظ می‌شوند. ابتدا بسته اولیه زبان را منتشر کنید.", failure: "دریافت وضعیت ترجمه ناموفق بود", saved: "تنظیمات ذخیره شد", save: "ذخیره تنظیمات", retry: "بارگذاری مجدد" },
  ru: { title: "Автоматический перевод магазина", enabled: "Автоматически обновлять все опубликованные языки этого магазина", publish: "Публиковать языковые пакеты после завершения", delay: "Единая задержка объединения (секунды)", loading: "Загрузка состояния автоматического перевода", DISABLED: "Автоматический перевод выключен", IDLE: "Отслеживаются изменения товаров", WAITING: "Ожидание автоматического перевода", QUEUED: "Автоматический перевод поставлен в очередь", RUNNING: "Выполняется автоматический перевод", PAUSED: "Перевод приостановлен", ATTENTION: "Некоторые данные требуют проверки", READY: "Переводы сохранены и готовы к публикации", manual: "Выполняется ручной перевод", help: "Настройка действует для магазина и всех опубликованных языков. Обрабатываются только новые или изменённые данные после включения; существующие переводы сохраняются. Сначала опубликуйте первый языковой пакет.", failure: "Не удалось загрузить состояние перевода", saved: "Настройки автоматического перевода сохранены", save: "Сохранить настройки", retry: "Загрузить снова" },
};
export const automaticTranslationCopy = (locale: UiLocale): Copy => locale === "zh-CN" ? zh : localized[locale];
