import type { StorefrontLocale } from "../types";
import type { QuoteTemplateField } from "./types";

/**
 * Labels used inside a customer-facing quotation.  The console language and
 * the quotation language are independent: operators may work in Chinese
 * while preparing a document for an English, Spanish, or Arabic customer.
 * Keep this dictionary local so changing the document language never waits
 * for a translation request.
 */
const STRINGS: Partial<Record<StorefrontLocale, Record<string, string>>> = {
  "zh-CN": {
    document_title: "报价单",
    merchant: "商家",
    quote_number: "报价单号",
    customer: "客户",
    contact: "联系人",
    date: "日期",
    submitted_date: "提交日期",
    company: "客户公司",
    valid_until: "有效期",
    email: "邮箱",
    phone: "电话",
    currency: "币种",
    serial_number: "序号",
    image: "图片",
    sku_code: "SKU",
    product_name: "商品名称",
    description: "商品描述",
    specification: "规格",
    category: "分类",
    tags: "标签",
    quantity: "数量",
    unit: "单位",
    packing_quantity: "装箱数量",
    carton_dimensions: "装箱尺寸",
    gross_weight: "毛重(kg)",
    carton_volume: "立方(m³)",
    minimum_order_quantity: "起订数",
    unit_price: "单价",
    line_total: "总价",
    total_volume: "总立方(m³)",
    total_gross_weight: "总毛重(kg)",
    total: "合计",
    notes: "备注",
    merchant_contact: "商家联系方式",
    quote_date: "报价日期",
    language: "当前语言",
    disclaimer: "此文件仅为报价申请草稿和价格预估，当前状态为待人工确认；在商家完成审核并签发正式报价前，不构成要约、承诺或正式报价。",
    configured: "已配置",
    separator: "、",
  },
  "en-US": {
    document_title: "QUOTATION",
    merchant: "Merchant",
    quote_number: "Quotation No.",
    customer: "Customer",
    contact: "Contact",
    date: "Date",
    submitted_date: "Submitted",
    company: "Company",
    valid_until: "Valid Until",
    email: "Email",
    phone: "Phone",
    currency: "Currency",
    serial_number: "No.",
    image: "Image",
    sku_code: "SKU",
    product_name: "Product",
    description: "Description",
    specification: "Specification",
    category: "Category",
    tags: "Tags",
    quantity: "Quantity",
    unit: "Unit",
    packing_quantity: "Units / Carton",
    carton_dimensions: "Carton Size",
    gross_weight: "Gross Weight (kg)",
    carton_volume: "Volume (m³)",
    minimum_order_quantity: "MOQ",
    unit_price: "Unit Price",
    line_total: "Amount",
    total_volume: "Total Volume (m³)",
    total_gross_weight: "Total Gross Weight (kg)",
    total: "Total",
    notes: "Notes",
    merchant_contact: "Merchant Contact",
    quote_date: "Quotation Date",
    language: "Language",
    disclaimer: "This document is a quotation request draft and price estimate only. It is pending merchant review and does not constitute an offer, commitment, or formal quotation until issued by the merchant.",
    configured: "Configured",
    separator: ", ",
  },
  es: {
    document_title: "COTIZACIÓN",
    merchant: "Vendedor",
    quote_number: "N.º de cotización",
    customer: "Cliente",
    contact: "Contacto",
    date: "Fecha",
    submitted_date: "Fecha de envío",
    company: "Empresa",
    valid_until: "Válida hasta",
    email: "Correo electrónico",
    phone: "Teléfono",
    currency: "Moneda",
    serial_number: "N.º",
    image: "Imagen",
    sku_code: "SKU",
    product_name: "Producto",
    description: "Descripción",
    specification: "Especificación",
    category: "Categoría",
    tags: "Etiquetas",
    quantity: "Cantidad",
    unit: "Unidad",
    packing_quantity: "Unidades / caja",
    carton_dimensions: "Medidas de la caja",
    gross_weight: "Peso bruto (kg)",
    carton_volume: "Volumen (m³)",
    minimum_order_quantity: "Cantidad mínima",
    unit_price: "Precio unitario",
    line_total: "Importe",
    total_volume: "Volumen total (m³)",
    total_gross_weight: "Peso bruto total (kg)",
    total: "Total",
    notes: "Notas",
    merchant_contact: "Contacto del vendedor",
    quote_date: "Fecha de cotización",
    language: "Idioma",
    disclaimer: "Este documento es solo un borrador de solicitud de cotización y una estimación de precios. Está pendiente de revisión del vendedor y no constituye una oferta, compromiso ni cotización formal hasta que el vendedor la emita.",
    configured: "Configurada",
    separator: ", ",
  },
  tr: {
    document_title: "FİYAT TEKLİFİ",
    merchant: "Satıcı",
    quote_number: "Teklif No.",
    customer: "Müşteri",
    contact: "İletişim",
    date: "Tarih",
    submitted_date: "Gönderim tarihi",
    company: "Şirket",
    valid_until: "Geçerlilik tarihi",
    email: "E-posta",
    phone: "Telefon",
    currency: "Para birimi",
    serial_number: "No.",
    image: "Görsel",
    sku_code: "SKU",
    product_name: "Ürün",
    description: "Açıklama",
    specification: "Özellik",
    category: "Kategori",
    tags: "Etiketler",
    quantity: "Miktar",
    unit: "Birim",
    packing_quantity: "Koli adedi",
    carton_dimensions: "Koli ölçüsü",
    gross_weight: "Brüt ağırlık (kg)",
    carton_volume: "Hacim (m³)",
    minimum_order_quantity: "Minimum sipariş",
    unit_price: "Birim fiyat",
    line_total: "Tutar",
    total_volume: "Toplam hacim (m³)",
    total_gross_weight: "Toplam brüt ağırlık (kg)",
    total: "Toplam",
    notes: "Notlar",
    merchant_contact: "Satıcı iletişim",
    quote_date: "Teklif tarihi",
    language: "Dil",
    disclaimer: "Bu belge yalnızca bir teklif talebi taslağı ve fiyat tahminidir. Satıcının incelemesine tabidir; satıcı tarafından düzenlenene kadar teklif, taahhüt veya resmi fiyat teklifi niteliği taşımaz.",
    configured: "Yapılandırıldı",
    separator: ", ",
  },
  ar: {
    document_title: "عرض سعر",
    merchant: "البائع",
    quote_number: "رقم عرض السعر",
    customer: "العميل",
    contact: "جهة الاتصال",
    date: "التاريخ",
    submitted_date: "تاريخ التقديم",
    company: "الشركة",
    valid_until: "صالح حتى",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    currency: "العملة",
    serial_number: "الرقم",
    image: "الصورة",
    sku_code: "SKU",
    product_name: "المنتج",
    description: "الوصف",
    specification: "المواصفات",
    category: "الفئة",
    tags: "الوسوم",
    quantity: "الكمية",
    unit: "الوحدة",
    packing_quantity: "العدد في الكرتون",
    carton_dimensions: "أبعاد الكرتون",
    gross_weight: "الوزن الإجمالي (كجم)",
    carton_volume: "الحجم (م³)",
    minimum_order_quantity: "الحد الأدنى للطلب",
    unit_price: "سعر الوحدة",
    line_total: "الإجمالي",
    total_volume: "الحجم الكلي (م³)",
    total_gross_weight: "الوزن الإجمالي الكلي (كجم)",
    total: "المجموع",
    notes: "ملاحظات",
    merchant_contact: "بيانات البائع",
    quote_date: "تاريخ عرض السعر",
    language: "اللغة",
    disclaimer: "هذه الوثيقة مسودة لطلب عرض سعر وتقدير للسعر فقط. وهي بانتظار مراجعة البائع ولا تشكل عرضاً أو التزاماً أو عرض سعر رسمي حتى يصدرها البائع.",
    configured: "تم الإعداد",
    separator: "، ",
  },
  ja: {
    document_title: "見積書",
    merchant: "販売者",
    quote_number: "見積番号",
    customer: "お客様",
    contact: "連絡先",
    date: "日付",
    submitted_date: "提出日",
    company: "会社名",
    valid_until: "有効期限",
    email: "メール",
    phone: "電話",
    currency: "通貨",
    serial_number: "番号",
    image: "画像",
    sku_code: "SKU",
    product_name: "商品名",
    description: "商品説明",
    specification: "仕様",
    category: "カテゴリー",
    tags: "タグ",
    quantity: "数量",
    unit: "単位",
    packing_quantity: "梱包数",
    carton_dimensions: "梱包サイズ",
    gross_weight: "総重量 (kg)",
    carton_volume: "容積 (m³)",
    minimum_order_quantity: "最小注文数",
    unit_price: "単価",
    line_total: "金額",
    total_volume: "総容積 (m³)",
    total_gross_weight: "総重量合計 (kg)",
    total: "合計",
    notes: "備考",
    merchant_contact: "販売者連絡先",
    quote_date: "見積日",
    language: "言語",
    disclaimer: "この文書は見積依頼の下書きおよび価格の目安です。販売者の確認前は、申し込み、約束、正式な見積書を構成しません。",
    configured: "設定済み",
    separator: "、",
  },
  ko: {
    document_title: "견적서",
    merchant: "판매자",
    quote_number: "견적 번호",
    customer: "고객",
    contact: "담당자",
    date: "날짜",
    submitted_date: "제출일",
    company: "회사",
    valid_until: "유효 기간",
    email: "이메일",
    phone: "전화",
    currency: "통화",
    serial_number: "번호",
    image: "이미지",
    sku_code: "SKU",
    product_name: "상품명",
    description: "상품 설명",
    specification: "규격",
    category: "분류",
    tags: "태그",
    quantity: "수량",
    unit: "단위",
    packing_quantity: "포장 수량",
    carton_dimensions: "포장 크기",
    gross_weight: "총중량 (kg)",
    carton_volume: "부피 (m³)",
    minimum_order_quantity: "최소 주문 수량",
    unit_price: "단가",
    line_total: "금액",
    total_volume: "총부피 (m³)",
    total_gross_weight: "총중량 합계 (kg)",
    total: "합계",
    notes: "비고",
    merchant_contact: "판매자 연락처",
    quote_date: "견적일",
    language: "언어",
    disclaimer: "이 문서는 견적 요청 초안 및 가격 예상치입니다. 판매자 검토 전에는 제안, 약정 또는 공식 견적을 구성하지 않습니다.",
    configured: "설정됨",
    separator: ", ",
  },
  pt: {
    document_title: "COTAÇÃO",
    merchant: "Vendedor",
    quote_number: "N.º da cotação",
    customer: "Cliente",
    contact: "Contato",
    date: "Data",
    submitted_date: "Data de envio",
    company: "Empresa",
    valid_until: "Válida até",
    email: "E-mail",
    phone: "Telefone",
    currency: "Moeda",
    serial_number: "N.º",
    image: "Imagem",
    sku_code: "SKU",
    product_name: "Produto",
    description: "Descrição",
    specification: "Especificação",
    category: "Categoria",
    tags: "Etiquetas",
    quantity: "Quantidade",
    unit: "Unidade",
    packing_quantity: "Unidades / caixa",
    carton_dimensions: "Dimensões da caixa",
    gross_weight: "Peso bruto (kg)",
    carton_volume: "Volume (m³)",
    minimum_order_quantity: "Quantidade mínima",
    unit_price: "Preço unitário",
    line_total: "Valor total",
    total_volume: "Volume total (m³)",
    total_gross_weight: "Peso bruto total (kg)",
    total: "Total",
    notes: "Observações",
    merchant_contact: "Contato do vendedor",
    quote_date: "Data da cotação",
    language: "Idioma",
    disclaimer: "Este documento é apenas um rascunho de solicitação de cotação e uma estimativa de preço. Está pendente de análise do vendedor e não constitui oferta, compromisso ou cotação formal até ser emitido pelo vendedor.",
    configured: "Configurada",
    separator: ", ",
  },
  fr: {
    document_title: "DEVIS",
    merchant: "Vendeur",
    quote_number: "N° de devis",
    customer: "Client",
    contact: "Contact",
    date: "Date",
    submitted_date: "Date d’envoi",
    company: "Entreprise",
    valid_until: "Valable jusqu’au",
    email: "E-mail",
    phone: "Téléphone",
    currency: "Devise",
    serial_number: "N°",
    image: "Image",
    sku_code: "SKU",
    product_name: "Produit",
    description: "Description",
    specification: "Spécification",
    category: "Catégorie",
    tags: "Étiquettes",
    quantity: "Quantité",
    unit: "Unité",
    packing_quantity: "Unités / carton",
    carton_dimensions: "Dimensions du carton",
    gross_weight: "Poids brut (kg)",
    carton_volume: "Volume (m³)",
    minimum_order_quantity: "Quantité minimale",
    unit_price: "Prix unitaire",
    line_total: "Montant",
    total_volume: "Volume total (m³)",
    total_gross_weight: "Poids brut total (kg)",
    total: "Total",
    notes: "Remarques",
    merchant_contact: "Coordonnées du vendeur",
    quote_date: "Date du devis",
    language: "Langue",
    disclaimer: "Ce document est uniquement un brouillon de demande de devis et une estimation de prix. Il reste soumis à la validation du vendeur et ne constitue ni une offre, ni un engagement, ni un devis officiel avant son émission par le vendeur.",
    configured: "Configurée",
    separator: ", ",
  },
  fa: {
    document_title: "پیش‌فاکتور",
    merchant: "فروشنده",
    quote_number: "شماره پیش‌فاکتور",
    customer: "مشتری",
    contact: "شخص تماس",
    date: "تاریخ",
    submitted_date: "تاریخ ارسال",
    company: "شرکت",
    valid_until: "معتبر تا",
    email: "ایمیل",
    phone: "تلفن",
    currency: "ارز",
    serial_number: "ردیف",
    image: "تصویر",
    sku_code: "SKU",
    product_name: "محصول",
    description: "توضیحات",
    specification: "مشخصات",
    category: "دسته‌بندی",
    tags: "برچسب‌ها",
    quantity: "تعداد",
    unit: "واحد",
    packing_quantity: "تعداد در کارتن",
    carton_dimensions: "ابعاد کارتن",
    gross_weight: "وزن ناخالص (کیلوگرم)",
    carton_volume: "حجم (متر مکعب)",
    minimum_order_quantity: "حداقل سفارش",
    unit_price: "قیمت واحد",
    line_total: "مبلغ",
    total_volume: "حجم کل (متر مکعب)",
    total_gross_weight: "وزن ناخالص کل (کیلوگرم)",
    total: "جمع کل",
    notes: "یادداشت‌ها",
    merchant_contact: "اطلاعات تماس فروشنده",
    quote_date: "تاریخ پیش‌فاکتور",
    language: "زبان",
    disclaimer: "این سند فقط پیش‌نویس درخواست قیمت و برآورد قیمت است. تا پیش از بررسی و صدور رسمی توسط فروشنده، پیشنهاد، تعهد یا پیش‌فاکتور رسمی محسوب نمی‌شود.",
    configured: "پیکربندی شده",
    separator: "، ",
  },
};

const FIELD_KEYS: Partial<Record<QuoteTemplateField, string>> = {
  serial_number: "serial_number",
  sku_code: "sku_code",
  product_name: "product_name",
  description: "description",
  specification: "specification",
  category: "category",
  tags: "tags",
  product_image: "image",
  quantity: "quantity",
  unit_code: "unit",
  packing_quantity: "packing_quantity",
  carton_dimensions: "carton_dimensions",
  gross_weight: "gross_weight",
  carton_volume: "carton_volume",
  minimum_order_quantity: "minimum_order_quantity",
  unit_price: "unit_price",
  line_total: "line_total",
  total_volume: "total_volume",
  total_gross_weight: "total_gross_weight",
  currency: "currency",
  quote_number: "quote_number",
  quote_date: "quote_date",
  customer_name: "customer",
  customer_company: "company",
  customer_email: "email",
  customer_phone: "phone",
  notes: "notes",
};

const PROFORMA_STRINGS: Partial<Record<StorefrontLocale, Record<string, string>>> = {
  "zh-CN": {
    title: "形式发票", sheet_name: "形式发票", invoice_number: "形式发票号", issue_date: "开票日期",
    seller: "卖方", buyer: "买方", seller_address: "卖方地址", buyer_address: "买方地址", valid_until: "有效期",
    subtotal: "商品小计", freight: "运费", grand_total: "应付总额", trade_terms: "贸易与交付",
    incoterm: "贸易术语", payment_terms: "付款条款", delivery_terms: "交货条款", shipment_method: "运输方式",
    port_of_loading: "装运港", port_of_destination: "目的港", bank_details: "收款银行信息", beneficiary_name: "收款人",
    bank_name: "银行名称", bank_address: "银行地址", bank_account_number: "银行账号", swift_code: "SWIFT / BIC", remarks: "附加说明",
  },
  "en-US": {
    title: "PROFORMA INVOICE", sheet_name: "Proforma Invoice", invoice_number: "PI No.", issue_date: "Issue Date",
    seller: "Seller", buyer: "Buyer", seller_address: "Seller Address", buyer_address: "Buyer Address", valid_until: "Valid Until",
    subtotal: "Subtotal", freight: "Freight", grand_total: "Amount Due", trade_terms: "Trade & Delivery",
    incoterm: "Incoterm", payment_terms: "Payment Terms", delivery_terms: "Delivery Terms", shipment_method: "Shipment Method",
    port_of_loading: "Port of Loading", port_of_destination: "Port of Destination", bank_details: "Banking Details", beneficiary_name: "Beneficiary",
    bank_name: "Bank Name", bank_address: "Bank Address", bank_account_number: "Account Number", swift_code: "SWIFT / BIC", remarks: "Remarks",
  },
  es: {
    title: "FACTURA PROFORMA", sheet_name: "Factura proforma", invoice_number: "N.º de proforma", issue_date: "Fecha de emisión",
    seller: "Vendedor", buyer: "Comprador", seller_address: "Dirección del vendedor", buyer_address: "Dirección del comprador", valid_until: "Válida hasta",
    subtotal: "Subtotal", freight: "Flete", grand_total: "Total a pagar", trade_terms: "Comercio y entrega",
    incoterm: "Incoterm", payment_terms: "Condiciones de pago", delivery_terms: "Condiciones de entrega", shipment_method: "Método de envío",
    port_of_loading: "Puerto de carga", port_of_destination: "Puerto de destino", bank_details: "Datos bancarios", beneficiary_name: "Beneficiario",
    bank_name: "Banco", bank_address: "Dirección del banco", bank_account_number: "Número de cuenta", swift_code: "SWIFT / BIC", remarks: "Observaciones",
  },
  tr: {
    title: "PROFORMA FATURA", sheet_name: "Proforma Fatura", invoice_number: "Proforma No.", issue_date: "Düzenleme tarihi",
    seller: "Satıcı", buyer: "Alıcı", seller_address: "Satıcı adresi", buyer_address: "Alıcı adresi", valid_until: "Geçerlilik tarihi",
    subtotal: "Ara toplam", freight: "Navlun", grand_total: "Ödenecek toplam", trade_terms: "Ticaret ve teslimat",
    incoterm: "Incoterm", payment_terms: "Ödeme koşulları", delivery_terms: "Teslimat koşulları", shipment_method: "Sevkiyat şekli",
    port_of_loading: "Yükleme limanı", port_of_destination: "Varış limanı", bank_details: "Banka bilgileri", beneficiary_name: "Lehtar",
    bank_name: "Banka adı", bank_address: "Banka adresi", bank_account_number: "Hesap numarası", swift_code: "SWIFT / BIC", remarks: "Açıklamalar",
  },
  ar: {
    title: "فاتورة أولية", sheet_name: "فاتورة أولية", invoice_number: "رقم الفاتورة الأولية", issue_date: "تاريخ الإصدار",
    seller: "البائع", buyer: "المشتري", seller_address: "عنوان البائع", buyer_address: "عنوان المشتري", valid_until: "صالحة حتى",
    subtotal: "المجموع الفرعي", freight: "الشحن", grand_total: "المبلغ المستحق", trade_terms: "التجارة والتسليم",
    incoterm: "شرط التجارة", payment_terms: "شروط الدفع", delivery_terms: "شروط التسليم", shipment_method: "طريقة الشحن",
    port_of_loading: "ميناء التحميل", port_of_destination: "ميناء الوصول", bank_details: "البيانات المصرفية", beneficiary_name: "المستفيد",
    bank_name: "اسم البنك", bank_address: "عنوان البنك", bank_account_number: "رقم الحساب", swift_code: "SWIFT / BIC", remarks: "ملاحظات إضافية",
  },
  ja: {
    title: "プロフォーマインボイス", sheet_name: "プロフォーマインボイス", invoice_number: "PI番号", issue_date: "発行日",
    seller: "売主", buyer: "買主", seller_address: "売主住所", buyer_address: "買主住所", valid_until: "有効期限",
    subtotal: "小計", freight: "運賃", grand_total: "支払総額", trade_terms: "取引・納品条件",
    incoterm: "インコタームズ", payment_terms: "支払条件", delivery_terms: "納品条件", shipment_method: "輸送方法",
    port_of_loading: "積出港", port_of_destination: "仕向港", bank_details: "銀行情報", beneficiary_name: "受取人",
    bank_name: "銀行名", bank_address: "銀行住所", bank_account_number: "口座番号", swift_code: "SWIFT / BIC", remarks: "備考",
  },
  ko: {
    title: "견적 송장", sheet_name: "견적 송장", invoice_number: "PI 번호", issue_date: "발행일",
    seller: "판매자", buyer: "구매자", seller_address: "판매자 주소", buyer_address: "구매자 주소", valid_until: "유효 기간",
    subtotal: "소계", freight: "운임", grand_total: "결제 총액", trade_terms: "거래 및 배송",
    incoterm: "인코텀즈", payment_terms: "결제 조건", delivery_terms: "납품 조건", shipment_method: "운송 방법",
    port_of_loading: "선적항", port_of_destination: "도착항", bank_details: "은행 정보", beneficiary_name: "수취인",
    bank_name: "은행명", bank_address: "은행 주소", bank_account_number: "계좌 번호", swift_code: "SWIFT / BIC", remarks: "비고",
  },
  pt: {
    title: "FATURA PROFORMA", sheet_name: "Fatura proforma", invoice_number: "N.º da proforma", issue_date: "Data de emissão",
    seller: "Vendedor", buyer: "Comprador", seller_address: "Endereço do vendedor", buyer_address: "Endereço do comprador", valid_until: "Válida até",
    subtotal: "Subtotal", freight: "Frete", grand_total: "Total a pagar", trade_terms: "Comércio e entrega",
    incoterm: "Incoterm", payment_terms: "Condições de pagamento", delivery_terms: "Condições de entrega", shipment_method: "Método de envio",
    port_of_loading: "Porto de embarque", port_of_destination: "Porto de destino", bank_details: "Dados bancários", beneficiary_name: "Beneficiário",
    bank_name: "Banco", bank_address: "Endereço do banco", bank_account_number: "Número da conta", swift_code: "SWIFT / BIC", remarks: "Observações",
  },
  fr: {
    title: "FACTURE PRO FORMA", sheet_name: "Facture pro forma", invoice_number: "N° de pro forma", issue_date: "Date d’émission",
    seller: "Vendeur", buyer: "Acheteur", seller_address: "Adresse du vendeur", buyer_address: "Adresse de l’acheteur", valid_until: "Valable jusqu’au",
    subtotal: "Sous-total", freight: "Fret", grand_total: "Total à payer", trade_terms: "Commerce et livraison",
    incoterm: "Incoterm", payment_terms: "Conditions de paiement", delivery_terms: "Conditions de livraison", shipment_method: "Mode d’expédition",
    port_of_loading: "Port de chargement", port_of_destination: "Port de destination", bank_details: "Coordonnées bancaires", beneficiary_name: "Bénéficiaire",
    bank_name: "Banque", bank_address: "Adresse de la banque", bank_account_number: "Numéro de compte", swift_code: "SWIFT / BIC", remarks: "Remarques",
  },
  fa: {
    title: "پیش‌فاکتور", sheet_name: "پیش‌فاکتور", invoice_number: "شماره پیش‌فاکتور", issue_date: "تاریخ صدور",
    seller: "فروشنده", buyer: "خریدار", seller_address: "نشانی فروشنده", buyer_address: "نشانی خریدار", valid_until: "معتبر تا",
    subtotal: "جمع جزء", freight: "هزینه حمل", grand_total: "مبلغ قابل پرداخت", trade_terms: "تجارت و تحویل",
    incoterm: "اینکوترمز", payment_terms: "شرایط پرداخت", delivery_terms: "شرایط تحویل", shipment_method: "روش حمل",
    port_of_loading: "بندر بارگیری", port_of_destination: "بندر مقصد", bank_details: "اطلاعات بانکی", beneficiary_name: "ذی‌نفع",
    bank_name: "نام بانک", bank_address: "نشانی بانک", bank_account_number: "شماره حساب", swift_code: "SWIFT / BIC", remarks: "توضیحات",
  },
};

const UNIT_TRANSLATIONS: Record<string, Partial<Record<StorefrontLocale, string>>> = {
  piece: { "zh-CN": "件", "en-US": "pcs", es: "uds.", tr: "adet", ar: "قطعة", ja: "個", ko: "개", pt: "un.", fr: "pces", fa: "عدد", ru: "шт." },
  set: { "zh-CN": "套", "en-US": "sets", es: "juegos", tr: "set", ar: "طقم", ja: "セット", ko: "세트", pt: "conj.", fr: "ensembles", fa: "مجموعه", ru: "компл." },
  pair: { "zh-CN": "对", "en-US": "pairs", es: "pares", tr: "çift", ar: "زوج", ja: "組", ko: "쌍", pt: "pares", fr: "paires", fa: "جفت", ru: "пар" },
  box: { "zh-CN": "盒", "en-US": "boxes", es: "cajas", tr: "kutu", ar: "علبة", ja: "箱", ko: "상자", pt: "caixas", fr: "boîtes", fa: "جعبه", ru: "коробки" },
  carton: { "zh-CN": "箱", "en-US": "cartons", es: "cartones", tr: "koli", ar: "كرتون", ja: "カートン", ko: "카톤", pt: "caixas", fr: "cartons", fa: "کارتن", ru: "коробки" },
};

const UNIT_ALIASES: Record<string, keyof typeof UNIT_TRANSLATIONS> = {
  pc: "piece", pcs: "piece", piece: "piece", pieces: "piece", unit: "piece", units: "piece", 个: "piece", 件: "piece",
  set: "set", sets: "set", 套: "set",
  pair: "pair", pairs: "pair", 对: "pair",
  box: "box", boxes: "box", 盒: "box",
  carton: "carton", cartons: "carton", ctn: "carton", 箱: "carton",
};

export function quoteText(locale: StorefrontLocale, key: string): string {
  return STRINGS[locale]?.[key] ?? STRINGS["en-US"]?.[key] ?? STRINGS["zh-CN"]?.[key] ?? key;
}

export function proformaText(locale: StorefrontLocale, key: string): string {
  return PROFORMA_STRINGS[locale]?.[key] ?? PROFORMA_STRINGS["en-US"]?.[key] ?? key;
}

export function quoteFieldLabel(locale: StorefrontLocale, field: QuoteTemplateField, fallback?: string): string {
  if (field === "carton_count") {
    const labels: Partial<Record<StorefrontLocale, string>> = { "zh-CN": "箱数", "en-US": "Cartons", es: "Cajas", tr: "Koli sayısı", ar: "عدد الكراتين", ja: "箱数", ko: "박스 수", pt: "Caixas", fr: "Cartons", fa: "تعداد کارتن", ru: "Коробки" };
    return labels[locale] ?? labels["en-US"]!;
  }
  const key = FIELD_KEYS[field];
  return key ? quoteText(locale, key) : (fallback ?? field);
}

export function quoteUnit(locale: StorefrontLocale, unitCode: string | undefined): string {
  const raw = String(unitCode || "piece").trim() || "piece";
  const canonical = UNIT_ALIASES[raw.toLowerCase()];
  return canonical ? UNIT_TRANSLATIONS[canonical][locale] ?? UNIT_TRANSLATIONS[canonical]["en-US"] ?? raw : raw;
}

export function quoteSeparator(locale: StorefrontLocale): string {
  return quoteText(locale, "separator");
}

/** Labels that can appear as keys in legacy SKU option snapshots. */
export const quoteOptionAliases: Record<string, string[]> = {
  specification: ["规格", "规格名称", "Specification", "Especificación", "Özellik", "المواصفات", "仕様", "규격", "Especificação", "Spécification", "مشخصات"],
  packing_quantity: ["装箱数量", "装箱数", "一箱个数", "Units / Carton", "Unidades / caja", "Koli adedi", "العدد في الكرتون", "梱包数", "포장 수량", "Unidades / caixa", "Unités / carton", "تعداد در کارتن"],
  carton_dimensions: ["装箱尺寸", "外箱尺寸", "箱规", "Carton Size", "Medidas de la caja", "Koli ölçüsü", "أبعاد الكرتون", "梱包サイズ", "포장 크기", "Dimensões da caixa", "Dimensions du carton", "ابعاد کارتن"],
  gross_weight: ["毛重", "箱毛重", "Gross Weight (kg)", "Peso bruto (kg)", "Brüt ağırlık (kg)", "الوزن الإجمالي (كجم)", "総重量 (kg)", "총중량 (kg)", "Peso bruto (kg)"],
  carton_volume: ["立方", "箱体积", "cbm", "Volume (m³)", "Volumen (m³)", "Hacim (m³)", "الحجم (م³)", "容積 (m³)", "부피 (m³)"],
  minimum_order_quantity: ["起订数", "起订量", "MOQ", "Minimum Order Quantity", "Cantidad mínima", "Minimum sipariş", "الحد الأدنى للطلب", "最小注文数", "최소 주문 수량", "Quantidade mínima"],
  total_volume: ["总立方", "总立方数", "total_volume", "Total Volume (m³)", "Volumen total (m³)", "Toplam hacim (m³)", "الحجم الكلي (م³)", "総容積 (m³)", "총부피 (m³)"],
  total_gross_weight: ["总毛重", "总毛重kg", "total_gross_weight", "Total Gross Weight (kg)", "Peso bruto total (kg)", "Toplam brüt ağırlık (kg)", "الوزن الإجمالي الكلي (كجم)", "総重量合計 (kg)", "총중량 합계 (kg)"],
};
